[build]
  # No build command needed for static HTML
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Enable SPA routing for the simulation page
[[redirects]]
  from = "/simulation"
  to = "/simulation.html"
  status = 200